config/routes.rb
Rails.application.routes.draw do
  resources :comments
  resources :families do
    resources :wish_lists
  end
  resources :family_memberships
  resources :page
  resources :permissions
  resources :relationships
  resources :sessions
  resources :wish_items
  resources :wish_lists
  resources :up_votes
  resources :upload_files

  resources :users do
    resources :wish_lists
    resources :families
  end

  get '/signup', to: 'users#new', as: 'signup'
  get '/login', to: 'sessions#new', as: 'login'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy', as: 'logout'

  get '/about', to: 'page#about', as: 'about'
  get '/contact', to: 'page#contact', as: 'contact'
  get '/help', to: 'page#help', as: 'help'
  get '/welcome', to: 'page#welcome', as: 'welcome'

  root 'page#welcome'
end

app/models/wish_list.rb
class WishList < ActiveRecord::Base
  belongs_to :user
  belongs_to :family

  has_many :wish_items

  scope :by_updated_at, -> { order :updated_at }
  scope :by_title, -> { order :updated_at }
end

app/controllers/wish_lists_controller.rb
class WishListsController < ApplicationController
  def index
    wish_lists
  end

  def new
    wish_list
  end

  def create
    if @wish_list = WishList.create(wish_list_params)
      redirect_to wish_list
    else
      redirect_back
    end
  end

  def edit
    wish_list
  end

  def update
    if wish_list.update(wish_list_params)
      flash[:success] = 'Wish list updated successfully'
      redirect_to wish_list
    else
      redirect_back
    end
  end

  def show
    wish_list
  end

  def destroy
    family = wish_list.family
    if wish_list.delete
      redirect_to family
    else
      flash[:error] = 'Could not delete wish list'
      redirect_back
    end
  end

  private

  def wish_list_params
    params.require(:wish_list).permit(
      :id,
      :user_id,
      :family_id,
      :created_at,
      :updated_at,
      :title,
    ) if params[:wish_list]
  end

  def wish_list
    @wish_list ||= WishList.where(id: params[:id]).first
    @wish_list ||= WishList.new(wish_list_params)
  end

  def wish_lists
    @wish_lists ||= user.wish_lists.order(:title)
    @wish_lists ||= WishList.order(:title)
  end

  def user
    @user ||= User.find_by_id params[:user_id]
    @user ||= User.new
  end
end

app/helpers/wish_lists_helper.rb
module WishListsHelper
end

app/views/wish_lists/_form.haml
= form_for @wish_list, class: 'col-md-8' do |f|
  = f.hidden_field :user_id, value: current_user.id
  = f.hidden_field :family_id, value: params[:family_id]
  .form-group
    = f.label :title
    = f.text_field :title
  .form-group
    = f.label :family_id
    = f.select :family_id, current_user.families.pluck(:name, :id)
  .form-group
    = f.submit "Save", class: 'btn btn-primary'

app/views/wish_lists/edit.html.haml
= link_to :back, class: 'btn btn-primary' do
  = fa_icon 'chevron-left'
  Back
%h1 Edit Wish List
= render 'form'

app/views/wish_lists/index.html.haml
= render 'shared/index', records: @wish_lists
= link_to :new_wish_list, class: 'btn btn-primary' do
  = fa_icon "plus-circle"
  New

app/views/wish_lists/new.html.haml
= link_to :back, class: 'btn btn-primary' do
  = fa_icon 'chevron-left'
  Back
%h1 New Wish List
= render 'form'

app/views/wish_lists/show.html.haml
.container.col-md-10.col-md-offset-1
  .col-md-12.page-header
    %h1
      = @wish_list.title
      Wish List
    %h4
      of
      = link_to @wish_list.user do
        = @wish_list.user.first_name
        = @wish_list.user.last_name
      - if @wish_list.family
        of the
        = link_to @wish_list.family do
          = @wish_list.family.name
          Family

  .row.col-md-12.form-group
    = link_to @wish_list.family, class: 'btn btn-primary' do
      = fa_icon 'chevron-left'
      Back
    - if @wish_list.user == current_user
      = link_to new_wish_item_path(wish_item: {wish_list_id: @wish_list}), class: 'btn btn-success' do
        = fa_icon 'plus-circle'
        New Wish Item
    - if @wish_list.user == current_user
      = link_to edit_wish_list_path(@wish_list),
        class: 'btn btn-warning' do
        = fa_icon :pencil
        Edit Wish List
    - if @wish_list.user == current_user
      = link_to @wish_list,
        method: :delete,
        confirm: 'Delete this wish list?',
        class: 'btn btn-danger' do
        = fa_icon :times
        Delete Wish List

  .row.col-md-12
    - @wish_list.wish_items.by_name.each do |wish_item|
      .panel.panel-default
        .panel-heading.panel-title
          .container
            = wish_item.name
            - if wish_item.url.present?
              = link_to parse_url(wish_item.url), target: '_blank', class: 'btn btn-primary' do
                = fa_icon :code
                Link
            - if wish_item.user == current_user
              = link_to edit_wish_item_path(wish_item), class: 'btn btn-primary' do
                = fa_icon 'pencil'
                Edit
              = link_to wish_item,
                method: :delete,
                confirm: 'Delete this item?',
                class: 'btn btn-danger' do
                = fa_icon :times
                Delete
            - if wish_item.user != current_user
              = button_tag class: 'btn btn-primary btn-show' do
                = fa_icon 'eye'
                Show Status
            %span.to-show
              = button_tag class: 'btn btn-primary btn-hide' do
                = fa_icon 'eye-slash'
                Hide Status
              - unless wish_item.user == current_user || wish_item.purchased_by_id
                = link_to wish_item_path(wish_item, "wish_item[purchased_by_id]" => current_user.id), method: :patch, class: 'btn btn-primary' do
                  = fa_icon :usd
                  Purchase
              - if current_user == wish_item.purchased_by
                = link_to wish_item_path(wish_item, "wish_item[purchased_by_id]" => ''),
                  confirm: 'Mark this item as un-purchased?',
                  method: :patch, class: 'btn btn-primary' do
                  = fa_icon :usd
                  Un-purchase
              - if wish_item.purchased_by && current_user != wish_item.user
                Purchased by
                = link_to wish_item.purchased_by do
                  = wish_item.purchased_by.first_name
                  = wish_item.purchased_by.last_name
        .panel-body.container
          = wish_item.description