config/routes.rb
Rails.application.routes.draw do
  resources :comments
  resources :families do
    resources :wish_lists
  end
  resources :family_memberships
  resources :page
  resources :permissions
  resources :relationships
  resources :sessions
  resources :wish_items
  resources :wish_lists
  resources :up_votes
  resources :upload_files

  resources :users do
    resources :wish_lists
    resources :families
  end

  get '/signup', to: 'users#new', as: 'signup'
  get '/login', to: 'sessions#new', as: 'login'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy', as: 'logout'

  get '/about', to: 'page#about', as: 'about'
  get '/contact', to: 'page#contact', as: 'contact'
  get '/help', to: 'page#help', as: 'help'
  get '/welcome', to: 'page#welcome', as: 'welcome'

  root 'page#welcome'
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :recipe
  belongs_to :user
end

app/models/dashboard.rb
class Dashboard < ActiveRecord::Base
  belongs_to :owner, polymorphic: true
end

app/models/family.rb
class Family < ActiveRecord::Base
  belongs_to :owner, class_name: 'User'
  has_many :family_memberships
  has_many :users, through: :family_memberships
  has_many :wish_lists

  accepts_nested_attributes_for :family_memberships

  scope :by_updated_at, ->{order :updated_at}

  def active_wish_lists
    WishList.where id: (wish_lists.map(&:user_id) & users.pluck(:id))
  end

  def user_count
    users.count
  end
end

app/models/family_membership.rb
class FamilyMembership < ActiveRecord::Base
  belongs_to :user
  belongs_to :family
end

app/models/permission.rb
class Permission < ActiveRecord::Base
  belongs_to :user
  belongs_to :family
end

app/models/permission_type.rb
class PermissionType < ActiveRecord::Base
end

app/models/relationship.rb
class Relationship < ActiveRecord::Base
  has_many :users
end

app/models/up_vote.rb
class UpVote < ActiveRecord::Base
  belongs_to :comment
  belongs_to :recipe
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  has_many :family_memberships
  has_many :families, through: :family_memberships
  has_many :dashboards, foreign_key: :owner_id
  has_many :wish_lists
  has_many :wish_items, through: :wish_lists

  validates :username, presence: true
  validates :first_name, presence: true

  validates :email,
    presence: true,
    uniqueness: true,
    format: {
      with: /.+@.+\..+/,
      message: 'must be the correct format'
    }

  validates :password, unless: -> { password.blank? },
    length: {
    minimum: 6
  },
    format: {
    with: /\A(?=.*[a-z])(?=.*[A-Z])(?=.*(_|[^\w]|\d)).+\z/,
    message: 'must contain one uppercase letter, one lowercase letter, and a symbol or number'
  }

  def self.with_username(username)
    where(username: username).first
  end

  def has_password?(given_password)
    authenticate given_password
  end
end

app/models/wish_item.rb
class WishItem < ActiveRecord::Base
  belongs_to :wish_list
  delegate :user, to: :wish_list
  belongs_to :purchased_by, class_name: "User"

  scope :by_name, ->{order :name}
end

app/models/wish_list.rb
class WishList < ActiveRecord::Base
  belongs_to :user
  belongs_to :family

  has_many :wish_items

  scope :by_updated_at, -> { order :updated_at }
  scope :by_title, -> { order :updated_at }
end

app/controllers/families_controller.rb
class FamiliesController < ApplicationController
  def index
    @joined = FamilyMembership.where(user_id: current_user.id).joins(:family)
    @unjoined = Family.by_updated_at - @joined.map(&:family)
  end

  def new
    family
  end

  def create
    if @family = Family.create(family_params)
      redirect_to family
    else
      redirect_back
    end
  end

  def edit
    family
  end

  def update
    family
  end

  def show
    family
  end

  def destroy
    if family.delete
      redirect_to family
    else
      flash[:error] = 'Could not delete wish list'
      redirect_back
    end
  end

  private

  def family_params
    params.require(:family).permit!
  end

  def family
    @family ||= Family.find(params[:id]) if params[:id]
    @family ||= Family.new(family_params) if params[:family]
    @family ||= Family.new

    @family.family_memberships.build unless @family.family_memberships.any?

    @family
  end

  def families
    @families ||= Family.by_updated_at
  end

  def user
    @user ||= User.find_by_id params[:user_id]
    @user ||= User.new
  end
end

app/controllers/page_controller.rb
class PageController < ApplicationController
  def show
    render id
  end

  def welcome
    redirect_to families_path if current_user
  end

  private

  def id
    params[:id]
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :set_up_session

  def new
  end

  def create
    if @session.valid_password?
      flash[:success] = 'Logged in'
      update_current_user @session.user
      redirect_to user_families_path(current_user)
    else
      render :new
    end
  end

  def destroy
    flash[:info] = 'Logged out'
    update_current_user_id nil
    redirect_to :root
  end

  private

  def set_up_session
    @session = Session.new(login_params)
  end

  def login_params
    if params[:session]
      params
        .require(:session)
        .permit(:username, :password)
    else
      params
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    user
  end

  def create
    if user.save
      flash[:success] = "User account created with username <strong>#{user.username}</strong>"
      redirect_to :login
    else
      render :new
    end
  end

  def edit
    user
  end

  def update
    if user.update(user_params)
      flash[:success] = "User account updated with username <strong>#{user.username}</strong>"
      redirect_to user
    else
      render :edit
    end
  end

  def show
    user
  end

  def index
    users
  end

  private

  def user
    @user ||= User.find(params[:id]) if params[:id]
    @user ||= User.new(user_params) if params[:user]
    @user ||= User.new
  end

  def users
    @users ||= User.order(:username)
  end

  def user_params
    params
      .require(:user)
      .permit(
        :username,
        :email,
        :first_name,
        :last_name,
        :password,
        :password_confirmation
      )
  end
end

app/controllers/wish_items_controller.rb
class WishItemsController < ApplicationController
  def index
    wish_items
  end

  def new
    wish_item
    wish_list
  end

  def create
    if WishItem.create(wish_item_params)
      redirect_to wish_list
    else
      redirect_back
    end
  end

  def edit
    wish_item
    wish_list
  end

  def update
    if wish_item.update(wish_item_params)
      flash[:success] = 'Wish item updated successfully'
      redirect_to wish_list
    else
      redirect_back
    end
  end

  def show
    wish_item
  end

  def destroy
    if wish_item.delete
      redirect_to wish_list
    else
      flash[:error] = 'Could not delete wish list'
      redirect_back
    end
  end

  private

  def wish_list
    @wish_list ||= wish_item.wish_list
  end

  def wish_item
    @wish_item ||= WishItem.where(id: params[:id]).first
    @wish_item ||= WishItem.new(wish_item_params)
  end

  def wish_items
    @wish_items ||= @wish_list.wish_items if @wish_list
    @wish_items ||= WishItem.all

    @wish_items.sort_by! do |i|
      i.title.downcase.strip
    end
  end

  def wish_item_params
    params.require(:wish_item).permit!
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_key(key)
    case key
    when :success
      :success
    when :info
      :info
    when :warning
      :warning
    when :danger, :error
      :danger
    end
  end

  def link_back
    link_to :back, class: 'btn btn-primary' do
      fa_icon('chevron-left') +
        ' Back'
    end
  end

  def parse_url(url)
    url = "http://" + url unless url[/^http/]

    url
  end
end

app/helpers/page_helper.rb
module PageHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||=
      User.where(id: session[:current_user_id]).first if session[:current_user_id]
  end

  def update_current_user(user)
    update_current_user_id(user.try :id)
  end

  def update_current_user_id(id)
    session[:current_user_id] = id
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/wish_items_helper.rb
module WishItemsHelper
end

app/helpers/wish_lists_helper.rb
module WishListsHelper
end

app/views/families/destroy.html.haml
%h1 WishLists#destroy
%p Find me in app/views/wish_lists/destroy.html.haml

app/views/families/edit.html.haml
%h1 WishLists#edit
%p Find me in app/views/wish_lists/edit.html.haml

app/views/families/index.html.haml
.col-md-12
  = link_to new_family_path, class: 'btn btn-primary' do
    = fa_icon('plus-circle')
    Add Family
.col-md-6
  %h2.page-header Joined Families
  - @joined.each do |family_membership|
    - family = family_membership.family
    .col-md-6
      .panel.panel-default
        .panel-heading
          = link_to family, class: 'panel-title' do
            The
            = family.name
            Family
        .panel-body.container
          .col-md-12
            = fa_icon :users
            Number of Users:
            = family.users.count
          .col-md-12
            = fa_icon 'file-text'
            Number of Wish Lists:
            = family.wish_lists.count
          .col-md-12
            %br
            = link_to family,
              class: 'btn btn-primary' do
              = fa_icon :eye
              View
            = link_to family_membership,
              method: :delete,
              confirm: 'Leave this family?',
              class: 'btn btn-danger' do
              = fa_icon :times
              Leave
.col-md-6
  %h2.page-header Unjoined Families
  - @unjoined.each do |family|
    .col-md-6
      .panel.panel-default
        .panel-heading
          = link_to family, class: 'panel-title' do
            The
            = family.name
            Family
        .panel-body.container
          .col-md-12
            = fa_icon :users
            Number of Users:
            = family.users.count
          .col-md-12
            = fa_icon 'file-text'
            Number of Wish Lists:
            = family.wish_lists.count
          .col-md-12
            %br
            = link_to family,
              class: 'btn btn-primary' do
              = fa_icon :eye
              View
            = link_to family_memberships_path(family_id: family.id,
              user_id: current_user.id),
              method: :post,
              class: 'btn btn-primary' do
              = fa_icon 'plus-circle'
              Join

app/views/families/new.html.haml
%h1 New Family
= form_for @family do |f|
  = f.fields_for :family_memberships, @family.family_memberships do |family_membership|
    = family_membership.hidden_field :user_id, value: current_user.id
    = family_membership.hidden_field :family_id, value: @family.id
  = f.hidden_field :owner_id, value: current_user.id
  .form-group
    = f.label :name
    = f.text_field :name
  .form-group
    = f.submit :create, class: 'btn btn-primary'

app/views/families/show.html.haml
%h1.page-header.col-md-12
  The
  = @family.name
  Family
.col-md-12
  = link_to :root, class: 'btn btn-primary' do
    = fa_icon 'chevron-left'
    Back
  - if @family.users.include? current_user
    = link_to new_wish_list_path(family_id: @family.id),
      class: 'btn btn-success' do
      = fa_icon 'plus-circle'
      Add Wish List
.col-md-6
  %h3 Users
  - @family.users.each do |user|
    .panel.panel-default
      .panel-heading
        = fa_icon :user
        = link_to user do
          = user.first_name
          = user.last_name
          = "(#{user.username})"
        - if @family.owner == user
          \-
          = fa_icon :sitemap
          Family Manager

.col-md-6.container
  %h3 Wish Lists
  - @family.wish_lists.each do |wish_list|
    .panel.panel-default
      .panel-heading
        .col-md-10
          = fa_icon 'file-text'
          = wish_list.title
          Wish List
          %br
          = fa_icon :user
          = link_to wish_list.user do
            = wish_list.user.first_name
            = wish_list.user.last_name
            = "(#{wish_list.user.username})"

        = link_to wish_list,
          class: 'btn btn-primary' do
          = fa_icon :eye
          View
.col-md-12
  - if @family.owner == current_user
    %h3 Danger Zone !
    - if current_user == @family.owner
      = link_to @family, method: :delete, confirm: 'Delete this family?', class: 'btn btn-danger' do
        = fa_icon 'times'
        Delete Family

app/views/session/new.html.haml
%div.page-header
  %h1 Log In
%div.col-md-12
  %div.col-md-4
    = form_for :session, class: 'form-horizontal' do |f|
      %div.form-group
        = f.text_field :user_name,
          class: 'form-control',
          placeholder: 'username'
      %div.form-group
        = f.password_field :password,
          class: 'form-control',
          placeholder: 'password'
      %div.actions
        = f.submit 'Log In', class: 'btn'