config/routes.rb
Rails.application.routes.draw do
  resources :comments
  resources :families do
    resources :wish_lists
  end
  resources :family_memberships
  resources :page
  resources :permissions
  resources :relationships
  resources :sessions
  resources :wish_items
  resources :wish_lists
  resources :up_votes
  resources :upload_files

  resources :users do
    resources :wish_lists
    resources :families
  end

  get '/signup', to: 'users#new', as: 'signup'
  get '/login', to: 'sessions#new', as: 'login'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy', as: 'logout'

  get '/about', to: 'page#about', as: 'about'
  get '/contact', to: 'page#contact', as: 'contact'
  get '/help', to: 'page#help', as: 'help'
  get '/welcome', to: 'page#welcome', as: 'welcome'

  root 'page#welcome'
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :recipe
  belongs_to :user
end

app/models/dashboard.rb
class Dashboard < ActiveRecord::Base
  belongs_to :owner, polymorphic: true
end

app/models/family.rb
class Family < ActiveRecord::Base
  belongs_to :owner, class_name: 'User'
  has_many :family_memberships
  has_many :users, through: :family_memberships
  has_many :wish_lists

  accepts_nested_attributes_for :family_memberships

  scope :by_updated_at, ->{order :updated_at}

  def active_wish_lists
    WishList.where id: (wish_lists.map(&:user_id) & users.pluck(:id))
  end

  def user_count
    users.count
  end
end

app/models/family_membership.rb
class FamilyMembership < ActiveRecord::Base
  belongs_to :user
  belongs_to :family
end

app/models/permission.rb
class Permission < ActiveRecord::Base
  belongs_to :user
  belongs_to :family
end

app/models/permission_type.rb
class PermissionType < ActiveRecord::Base
end

app/models/relationship.rb
class Relationship < ActiveRecord::Base
  has_many :users
end

app/models/up_vote.rb
class UpVote < ActiveRecord::Base
  belongs_to :comment
  belongs_to :recipe
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  has_many :family_memberships
  has_many :families, through: :family_memberships
  has_many :dashboards, foreign_key: :owner_id
  has_many :wish_lists
  has_many :wish_items, through: :wish_lists

  validates :username, presence: true
  validates :first_name, presence: true

  validates :email,
    presence: true,
    uniqueness: true,
    format: {
      with: /.+@.+\..+/,
      message: 'must be the correct format'
    }

  validates :password, unless: -> { password.blank? },
    length: {
    minimum: 6
  },
    format: {
    with: /\A(?=.*[a-z])(?=.*[A-Z])(?=.*(_|[^\w]|\d)).+\z/,
    message: 'must contain one uppercase letter, one lowercase letter, and a symbol or number'
  }

  def self.with_username(username)
    where(username: username).first
  end

  def has_password?(given_password)
    authenticate given_password
  end
end

app/models/wish_item.rb
class WishItem < ActiveRecord::Base
  belongs_to :wish_list
  delegate :user, to: :wish_list
  belongs_to :purchased_by, class_name: "User"

  scope :by_name, ->{order :name}
end

app/models/wish_list.rb
class WishList < ActiveRecord::Base
  belongs_to :user
  belongs_to :family

  has_many :wish_items

  scope :by_updated_at, -> { order :updated_at }
  scope :by_title, -> { order :updated_at }
end

app/controllers/families_controller.rb
class FamiliesController < ApplicationController
  def index
    @joined = FamilyMembership.where(user_id: current_user.id).joins(:family)
    @unjoined = Family.by_updated_at - @joined.map(&:family)
  end

  def new
    family
  end

  def create
    if @family = Family.create(family_params)
      redirect_to family
    else
      redirect_back
    end
  end

  def edit
    family
  end

  def update
    family
  end

  def show
    family
  end

  def destroy
    if family.delete
      redirect_to family
    else
      flash[:error] = 'Could not delete wish list'
      redirect_back
    end
  end

  private

  def family_params
    params.require(:family).permit!
  end

  def family
    @family ||= Family.find(params[:id]) if params[:id]
    @family ||= Family.new(family_params) if params[:family]
    @family ||= Family.new

    @family.family_memberships.build unless @family.family_memberships.any?

    @family
  end

  def families
    @families ||= Family.by_updated_at
  end

  def user
    @user ||= User.find_by_id params[:user_id]
    @user ||= User.new
  end
end

app/controllers/page_controller.rb
class PageController < ApplicationController
  def show
    render id
  end

  def welcome
    redirect_to families_path if current_user
  end

  private

  def id
    params[:id]
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    user
  end

  def create
    if user.save
      flash[:success] = "User account created with username <strong>#{user.username}</strong>"
      redirect_to :login
    else
      render :new
    end
  end

  def edit
    user
  end

  def update
    if user.update(user_params)
      flash[:success] = "User account updated with username <strong>#{user.username}</strong>"
      redirect_to user
    else
      render :edit
    end
  end

  def show
    user
  end

  def index
    users
  end

  private

  def user
    @user ||= User.find(params[:id]) if params[:id]
    @user ||= User.new(user_params) if params[:user]
    @user ||= User.new
  end

  def users
    @users ||= User.order(:username)
  end

  def user_params
    params
      .require(:user)
      .permit(
        :username,
        :email,
        :first_name,
        :last_name,
        :password,
        :password_confirmation
      )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_key(key)
    case key
    when :success
      :success
    when :info
      :info
    when :warning
      :warning
    when :danger, :error
      :danger
    end
  end

  def link_back
    link_to :back, class: 'btn btn-primary' do
      fa_icon('chevron-left') +
        ' Back'
    end
  end

  def parse_url(url)
    url = "http://" + url unless url[/^http/]

    url
  end
end

app/helpers/page_helper.rb
module PageHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||=
      User.where(id: session[:current_user_id]).first if session[:current_user_id]
  end

  def update_current_user(user)
    update_current_user_id(user.try :id)
  end

  def update_current_user_id(id)
    session[:current_user_id] = id
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/wish_items_helper.rb
module WishItemsHelper
end

app/helpers/wish_lists_helper.rb
module WishListsHelper
end

app/views/layouts/application.html.haml
!!! 5
%html{lang: "en"}
  %head
    %title Wishlists

    = stylesheet_link_tag    'application',
      media: 'all',
      'data-turbolinks-track' => true
    = javascript_include_tag 'application',
      'data-turbolinks-track' => true
    = csrf_meta_tags
    = render 'shared/favicon'
  %body
    = render 'shared/navigation'

    .container
      .col-md-12.container
        = render 'shared/flash_messages'
        = yield

app/views/page/about.html.haml
.col-md-2
.col-md-8
  .page-header
    %h1 About
  %p.lead
    akWishlists is a site for familial organization when
    it comes to buying gifts for others. It ensures people
    do not buy the same item more than once, and it is extensible
    to allow for other cooperative family functions.
  = link_back
.col-md-2

app/views/page/contact.html.erb
<h1>Page#contact</h1>
<p>Find me in app/views/page/contact.html.erb</p>

app/views/page/contact.html.haml
.col-md-12.page-header
  %h1 Contact
.col-md-12
  %address.lead
    Andrew Kofink
    %br
    = link_to 'mailto:ajkofink@gmail.com' do
      ajkofink@gmail.com
    %br
    = link_to 'http://akofink.com', target: '_blank' do
      = fa_icon 'code'
    = link_to 'https://twitter.com/akofink', target: '_blank' do
      = fa_icon 'twitter'
    = link_to 'https://github.com/akofink', target: '_blank' do
      = fa_icon 'github'

app/views/page/help.html.erb
<h1>Page#help</h1>
<p>Find me in app/views/page/help.html.erb</p>

app/views/page/help.html.haml
.col-md-12.page-header
  %h1 Help
.col-md-12
  %p.lead
    As the project is still in its early stages, please direct any questions to
    = link_to 'me', :contact
    directly via email.

app/views/page/welcome.html.haml
.col-md-1

.jumbotron.col-md-10
  .container.text-center
    %h1 akWishlists
    %p
      the easiest way to share wish lists among family and friends
    .col-md-12.container
      .col-md-4
        = link_to about_path, role: "button", class: "btn btn-primary btn-lg" do
          = fa_icon 'info-circle'
          Learn more
      .col-md-4
        = link_to signup_path, role: "button", class: "btn btn-primary btn-lg" do
          = fa_icon 'user'
          Sign Up
      .col-md-4
        = link_to login_path, role: "button", class: "btn btn-primary btn-lg" do
          = fa_icon 'sign-in'
          Log In

.col-md-1

app/views/shared/_back.html.haml
- path ||= :back
= link_to path, class: 'btn btn-primary' do
  = fa_icon 'chevron-left'
  Back

app/views/shared/_favicon.html.haml
= favicon_link_tag "favicon.ico"

app/views/shared/_flash_messages.html.haml
- flash.each do |key, value|
  .col-md-12.alert.alert-dismissable{role: 'alert', class: "alert-#{flash_key(key)}"}
    = button_tag type: 'button', class: 'close', data: {dismiss: 'alert'} do
      = fa_icon 'times'
    = value.html_safe

app/views/shared/_form_errors.html.haml
- if model.errors.any?
  .form_errors.alert.alert-dismissable.alert-danger{role: 'alert'}
    = button_tag type: 'button', class: 'close', data: {dismiss: 'alert'} do
      = fa_icon 'times'
    %ul
    - model.errors.full_messages.each do |message|
      %li
        = message

app/views/shared/_index.html.haml
- model ||= (records.first || params[:controller].classify.constantize.new).class
- records ||= model.all
.page-header
  %h1
    = model.to_s.titleize.pluralize
.table-responsive
  %table.table.table-striped.table-hover
    %tr
      - model.column_names.each do |column_name|
        %th
          = column_name
    - records.each do |instance|
      %tr
        - model.column_names.each do |column_name|
          %td
            = link_to instance do
              = instance.try column_name.to_sym

app/views/shared/_navigation.html.haml
%nav.navbar.navbar-inverse{role: 'naviagation'}
  .container
    .col-md-12
      .navbar-header
        = button_tag '', class: 'navbar-toggle', data: { toggle: 'collapse', target: 'nav-collapse' } do
          = fa_icon 'bars'
        = link_to :root, class: 'navbar-brand' do
          akWishlists
          = fa_icon 'gift'
      .collapse.navbar-collapse
        %ul.nav.navbar-nav.navbar-right
          %li.dropdown
            = link_to '#', class: 'dropdown-toggle', data: { toggle: 'dropdown' } do
              = fa_icon 'info'
            %ul.dropdown-menu{role: 'menu'}
              %li
                = link_to :about do
                  About
                  = fa_icon 'cubes', class: 'pull-right'
              %li
                = link_to :contact do
                  Contact
                  = fa_icon 'phone', class: 'pull-right'
              %li
                = link_to :help do
                  Help
                  = fa_icon 'question', class: 'pull-right'
          - if current_user
            %li.dropdown
              = link_to '#', class: 'dropdown-toggle', data: { toggle: 'dropdown' } do
                = fa_icon 'archive'
              %ul.dropdown-menu{role: 'menu'}
                %li
                  = link_to user_wish_lists_path(current_user) do
                    Wish Lists
                    = fa_icon 'list', class: 'pull-right'
          %li.dropdown
            = link_to '#', class: 'dropdown-toggle', data: { toggle: 'dropdown' } do
              = fa_icon 'sliders'
            %ul.dropdown-menu{role: 'menu'}
              %li
                - if current_user
                  = link_to current_user do
                    Account
                    = fa_icon 'user', class: 'pull-right'
              %li
                - if current_user
                  = link_to :logout, method: 'delete' do
                    Logout
                    = fa_icon 'sign-out', class: 'pull-right'
                - else
                  = link_to :login do
                    Log In
                    = fa_icon 'sign-in', class: 'pull-right'
                  = link_to :signup do
                    Sign Up
                    = fa_icon 'user', class: 'pull-right'